name: Builds

on:
  push:
    branches: main
    paths:
      - Makefile
      - shared.mk
      - 'examples/**'
      - 'src/**'
      - '.github/workflows/build_tests.yaml'
  pull_request:
    branches: main
    paths:
      - Makefile
      - shared.mk
      - 'examples/**'
      - 'src/**'
      - '.github/workflows/build_tests.yaml'

jobs:
  # GitHub Currently only supports running directly on Ubuntu,
  # for any other Linux we need to use a container.

  fedora-rawhide:
    runs-on: ubuntu-latest

    container:
      image: fedora:rawhide

    steps:
      - name: Install tools/deps
        run: |
          dnf -y install git wget clang llvm compiler-rt lld make wasi-libc-devel cargo rust rust-std-static-wasm32-unknown-unknown rust-std-static-wasm32-wasi
          wget -O- https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-20/libclang_rt.builtins-wasm32-wasi-20.0.tar.gz | tar --strip-components=1 -xvzf - -C $(dirname $(clang -print-runtime-dir))

      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: make
        run: make V=1 E=1 all
